force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <description>Passenger Object containing information of a passenger</description>
    <label>Passenger</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email of the passenger</description>
    <inlineHelpText>Email of the passenger</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Travel__c/Travel__c.object-meta.xml
<CustomObject>
    <description>Object representing travel data</description>
    <label>Travel</label>
    <nameField>
        <label>Destination</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel__c/fields/Mode_of_Travel__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Travel__c</fullName>
    <description>Select the mode of travel</description>
    <inlineHelpText>Select the mode of travel</inlineHelpText>
    <label>Mode of Travel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>Flight</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Travel__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>source city of your travel</description>
    <externalId>true</externalId>
    <inlineHelpText>source city of your travel</inlineHelpText>
    <label>Source</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Travel__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Journey Start Date</description>
    <inlineHelpText>Journey Start Date</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TravelingPassenger__c/TravelingPassenger__c.object-meta.xml
<CustomObject>
    <description>Traveling Passengers</description>
    <label>TravelingPassenger</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>TravelingPassenger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TravelingPassengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelingPassenger__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>TravelingPassengers</relationshipLabel>
    <relationshipName>TravelingPassengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TravelingPassenger__c/fields/Travel__c.field-meta.xml
<CustomField>
    <fullName>Travel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Travel</label>
    <referenceTo>Travel__c</referenceTo>
    <relationshipLabel>TravelingPassengers</relationshipLabel>
    <relationshipName>TravelingPassengers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/notifyPassengers.cls
public with sharing class notifyPassengers implements Schedulable{
   public void execute(SchedulableContext sc){
    Datetime today = Datetime.now().date();
    Datetime tommorrow = today.addDays(1);

    List<TravelingPassenger__c> tps = [SELECT Id, Travel__c, Travel__r.Name, Travel__r.Source__c, Passenger__c, Passenger__r.Name,Passenger__r.email__c, Travel__r.Start_Date__c, Travel__r.Mode_of_Travel__c FROM TravelingPassenger__c WHERE Travel__r.Start_Date__c < :tommorrow AND Travel__r.Start_Date__c >= :today];
    utils.sendmailAlert(tps);
    for(TravelingPassenger__c tp: tps){
        List<String> data = utils.prepareAlert(tp);
        utils.sendData(data[0] + '\n' + data[1]);
    }
   }
}