force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <description>Passenger Object containing information of a passenger</description>
    <label>Passenger</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel__c/Travel__c.object-meta.xml
<CustomObject>
    <description>Object representing travel data</description>
    <label>Travel</label>
    <nameField>
        <label>Destination</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Destination reaching date</description>
    <inlineHelpText>Destination reaching date</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Travel__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>source city of your travel</description>
    <externalId>true</externalId>
    <inlineHelpText>source city of your travel</inlineHelpText>
    <label>Source</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Travel__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Journey Start Date</description>
    <inlineHelpText>Journey Start Date</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TravelingPassenger__c/TravelingPassenger__c.object-meta.xml
<CustomObject>
    <description>Traveling Passengers</description>
    <label>TravelingPassenger</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>TravelingPassenger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TravelingPassengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelingPassenger__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>TravelingPassengers</relationshipLabel>
    <relationshipName>TravelingPassengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TravelingPassenger__c/fields/Travel__c.field-meta.xml
<CustomField>
    <fullName>Travel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Travel</label>
    <referenceTo>Travel__c</referenceTo>
    <relationshipLabel>TravelingPassengers</relationshipLabel>
    <relationshipName>TravelingPassengers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TravelsDataController.cls
public with sharing class TravelsDataController {
    @AuraEnabled(cacheable=true)
    public static List<Travel__c> getTravelData() {
        return [SELECT Id, Name, Source__c, Start_date__c, End_date__c FROM Travel__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<TravelingPassenger__c> getPassengers(Id travelId){
        try {
            return [SELECT Id, Passenger__r.Name FROM TravelingPassenger__c WHERE Travel__c = :travelId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteRecord(Id travelId){
        List<TravelingPassenger__c> tps = [ SELECT Id, Travel__c FROM TravelingPassenger__c WHERE Travel__c = :travelId ];
        List<Travel__c> travels = [SELECT Id FROM Travel__c WHERE Id = :travelId ];
        try{
            delete tps;
            delete travels;
        }catch(DmlException e){
            throw new AuraHandledException('failed to delete' + e.getMessage());
        }
    }
}